
# Androguard is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Androguard is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Androguard.  If not, see <http://www.gnu.org/licenses/>.

# frameworks/base/core/res/AndroidManifest.xml

# This list is also updated periodically with scripts/update_android_permissions.py
# ######################################### PERMISSIONS ###################
# flake8: noqa
DVM_PERMISSIONS = {
    'MANIFEST_PERMISSION': {
        'SEND_SMS': ['dangerous', '发送 SMS 短信', '允许应用程序发送短信。恶意应用程序可能会在未经您确认的情况下发送消息，从而让您损失钱财。'],
        'SEND_SMS_NO_CONFIRMATION': ['dangerous', '发送 SMS 短信', '通过消息应用程序发送短信，无需用户输入或确认。'],
        'CALL_PHONE': ['dangerous', '直接拨打电话号码', '允许应用程序在无需您干预的情况下拨打电话号码。恶意应用程序可能会导致您的电话账单上出现意外呼叫。请注意，这不允许应用程序拨打紧急号码。'],
        'RECEIVE_SMS': ['dangerous', '接收 SMS 短信', '允许应用程序接收并处理 SMS 消息。恶意应用程序可能会监视您的消息或删除它们而不向您显示它们。'],
        'RECEIVE_MMS': ['dangerous', '接收 MMS 彩信', '允许应用程序接收并处理 MMS 彩信。恶意应用程序可能会监视您的消息或删除它们而不向您显示它们。'],
        'READ_SMS': ['dangerous', '读取 SMS 或 MMS', '允许应用程序读取手机或 SIM 卡上存储的 SMS 短信。恶意应用程序可能会读取您的机密消息。'],
        'WRITE_SMS': ['dangerous', '写入 SMS 或 MMS', '允许应用程序写入存储在手机或 SIM 卡上的短信。恶意应用程序可能会删除您的消息。'],
        'RECEIVE_WAP_PUSH': ['dangerous', '接收 WAP', '允许应用程序接收和处理 WAP 消息。恶意应用程序可能会监视您的消息或删除它们而不向您显示它们。'],
        'READ_CONTACTS': ['dangerous', '读取联系人数据', '允许应用程序读取您手机上存储的所有联系人（地址）数据。恶意应用程序可以利用此将您的数据发送给其他人。'],
        'WRITE_CONTACTS': ['dangerous', '写入联系人数据', '允许应用程序写入手机上存储的联系人（地址）数据。恶意应用程序可以利用它来删除或修改您的联系数据。'],
        'READ_PROFILE': ['dangerous', '读取用户的个人资料数据', '允许应用程序读取用户的个人资料数据。'],
        'WRITE_PROFILE': ['dangerous', '写入用户的个人资料数据', '允许应用程序写入(但不读取)用户的个人资料数据。'],
        'READ_SOCIAL_STREAM': ['dangerous', '读取用户的社交流', '允许应用程序读取用户的社交流。'],
        'WRITE_SOCIAL_STREAM': ['dangerous', '写入用户的社交流', '允许应用程序写入用户的社交流'],
        'READ_CALENDAR': ['dangerous', '读取日历事件', '允许应用程序读取手机上存储的所有日历事件。恶意应用程序可以利用此将您的日历事件发送给其他人。'],
        'WRITE_CALENDAR': ['dangerous', '添加或修改日历事件并向客人发送电子邮件', '允许应用程序添加或更改日历上的事件，这可能会向客人发送电子邮件。恶意应用程序可以利用它来删除或修改您的日历事件或向客人发送电子邮件。'],
        'READ_USER_DICTIONARY': ['dangerous', '读取用户定义的字典', '允许应用程序读取用户可能存储在用户词典中的任何私人单词、名称和短语。'],
        'WRITE_USER_DICTIONARY': ['normal', '写入用户定义的字典', '允许应用程序将新单词写入用户词典。'],
        'READ_HISTORY_BOOKMARKS': ['dangerous', '读取浏览器的历史记录和书签', '允许应用程序读取浏览器访问过的所有 URL 以及浏览器的所有书签。'],
        'WRITE_HISTORY_BOOKMARKS': ['dangerous', '写入浏览器的历史记录和书签', '允许应用程序修改手机上存储的浏览器历史记录或书签。恶意应用程序可以利用它来删除或修改您的浏览器数据。'],
        'SET_ALARM': ['normal', '在闹钟中设置闹钟', '允许应用程序在已安装的闹钟应用程序中设置闹钟。某些闹钟应用程序可能无法实现此功能。'],
        'ACCESS_FINE_LOCATION': ['dangerous', '精确 (GPS) 位置', '访问精确位置源，例如手机上的全球定位系统（如果有）。恶意应用程序可以利用此信息来确定您所在的位置，并可能消耗额外的电池电量。'],
        'ACCESS_COARSE_LOCATION': ['dangerous', '粗略 (network-based) 位置', '访问粗略位置源（例如移动网络数据库）以确定手机的大概位置（如果有）。恶意应用程序可以利用此信息来确定您的大致位置。'],
        'ACCESS_MOCK_LOCATION': ['dangerous', '模拟位置源用于测试', '创建模拟位置源以进行测试。恶意应用程序可以使用它来覆盖由实时位置源（例如 GPS 或网络提供商）返回的位置和/或状态。'],
        'ACCESS_LOCATION_EXTRA_COMMANDS': ['normal', '访问额外的位置提供程序命令', '访问额外的位置提供程序命令。恶意应用程序可能会利用此问题干扰 GPS 或其他位置源的运行。'],
        'INSTALL_LOCATION_PROVIDER': ['signatureOrSystem', '权限以安装位置提供程序', '创建模拟位置源以进行测试。恶意应用程序可以使用它来覆盖由实时位置源（例如 GPS 或网络提供商）返回的位置和/或状态，或者监视您的位置并向外部源报告您的位置。'],
        'INTERNET': ['normal', '完全互联网接入', '允许应用程序创建网络套接字.'],
        'ACCESS_NETWORK_STATE': ['normal', '查看网络状态', '允许应用程序查看所有网络的状态。'],
        'ACCESS_WIFI_STATE': ['normal', '查看 Wi-Fi 状态', '允许应用程序查看有关 Wi-Fi 状态的信息。'],
        'BLUETOOTH': ['normal', '创建蓝牙连接', '允许应用程序连接到配对的蓝牙设备。'],
        'NFC': ['normal', '控制NFC', '允许应用程序与近场通信 (NFC) 标签、卡和读卡器进行通信。'],
        'USE_SIP': ['dangerous', '拨打/接听互联网电话', '允许应用程序使用 SIP 服务拨打/接听 Internet 电话。'],
        'ACCOUNT_MANAGER': ['signature', '担任账户管理器服务', '允许应用程序调用帐户验证器。'],
        'GET_ACCOUNTS': ['dangerous', '列出帐户', '允许访问帐户服务中的帐户列表.'],
        'AUTHENTICATE_ACCOUNTS': ['dangerous', '担任帐户验证器', '允许应用程序使用帐户管理器的帐户验证器功能，包括创建帐户以及获取和设置其密码。'],
        'USE_CREDENTIALS': ['dangerous', '使用帐户的身份验证凭据', '允许应用程序请求身份验证令牌。'],
        'MANAGE_ACCOUNTS': ['dangerous', '管理帐户列表', '允许应用程序执行添加和删除帐户以及删除其密码等操作。'],
        'MODIFY_AUDIO_SETTINGS': ['normal', '更改音频设置', '允许应用程序修改全局音频设置，例如音量和路由。'],
        'RECORD_AUDIO': ['dangerous', '录制音频', '允许应用程序访问音频录制路径。'],
        'CAMERA': ['dangerous', '拍摄照片和视频', '允许应用程序使用相机拍摄照片和视频。这允许应用程序收集相机随时看到的图像。'],
        'VIBRATE': ['normal', '控制振动器', '允许应用程序控制振动器。'],
        'FLASHLIGHT': ['normal', '控制手电筒', '允许应用程序控制手电筒。'],
        'ACCESS_USB': ['signatureOrSystem', '访问 USB 设备', '允许应用程序访问 USB 设备。'],
        'HARDWARE_TEST': ['signature', '测试硬件', '允许应用程序控制各种外设以进行硬件测试。'],
        'PROCESS_OUTGOING_CALLS': ['dangerous', '拦截拨出电话', '允许应用程序处理拨出电话并更改要拨打的号码。恶意应用程序可能会监视、重定向或阻止拨出呼叫。'],
        'MODIFY_PHONE_STATE': ['signatureOrSystem', '修改手机状态', '允许应用程序控制设备的电话功能。具有此权限的应用程序可以切换网络、打开和关闭电话收音机等，而无需通知您。'],
        'READ_PHONE_STATE': ['dangerous', '读取手机状态和身份', '允许应用程序访问设备的电话功能。具有此权限的应用程序可以确定该手机的电话号码和序列号、呼叫是否处于活动状态、呼叫所连接的号码等。'],
        'WRITE_EXTERNAL_STORAGE': ['dangerous', '读取/修改/删除外部存储内容', '允许应用程序写入外部存储。'],
        'READ_EXTERNAL_STORAGE': ['dangerous', '读取外部存储内容', '允许应用程序从外部存储中读取数据。'],
        'WRITE_SETTINGS': ['dangerous', '修改全局系统设置', '允许应用程序修改系统的设置数据。恶意应用程序可能会损坏您的系统配置。'],
        'WRITE_SECURE_SETTINGS': ['signatureOrSystem', '修改安全系统设置', '允许应用程序修改系统的安全设置数据。不适合普通应用程序使用。'],
        'WRITE_GSERVICES': ['signatureOrSystem', '修改Google服务地图', '允许应用程序修改 Google 服务地图。不适合普通应用程序使用。'],
        'EXPAND_STATUS_BAR': ['normal', '展开/折叠状态栏', '允许应用程序展开或折叠状态栏。'],
        'GET_TASKS': ['dangerous', '检索正在运行的应用程序', '允许应用程序检索有关当前和最近运行的任务的信息。可能允许恶意应用程序发现有关其他应用程序的私人信息。'],
        'REORDER_TASKS': ['normal', '重新排序正在运行的应用程序', '允许应用程序将任务移至前台和后台。恶意应用程序可能会在您无法控制的情况下将自己推到前台。'],
        'CHANGE_CONFIGURATION': ['signatureOrSystem', '更改用户界面设置', '允许应用程序更改当前配置，例如区域设置或整体字体大小'],
        'RESTART_PACKAGES': ['normal', '杀死后台进程', '允许应用程序终止其他应用程序的后台进程，即使内存不低。'],
        'KILL_BACKGROUND_PROCESSES': ['normal', '杀死后台进程', '允许应用程序终止其他应用程序的后台进程，即使内存不低。'],
        'FORCE_STOP_PACKAGES': ['signature', '强制停止其他应用程序', '允许一个应用程序强制停止其他应用程序。'],
        'DUMP': ['signatureOrSystem', '检索系统内部状态', '允许应用程序检索系统的内部状态。恶意应用程序可能会检索它们通常不需要的各种私人和安全信息。'],
        'SYSTEM_ALERT_WINDOW': ['dangerous', '显示系统级警报', '允许应用程序显示系统警报窗口。恶意应用程序可以占据手机的整个屏幕。'],
        'SET_ANIMATION_SCALE': ['dangerous', '修改全局动画速度', '允许应用程序随时更改全局动画速度（更快或更慢的动画）。'],
        'PERSISTENT_ACTIVITY': ['dangerous', '使应用程序始终运行', '允许应用程序将其自身的某些部分持久化，以便系统无法将其用于其他应用程序。'],
        'GET_PACKAGE_SIZE': ['normal', '测量应用程序存储空间', '允许应用程序找出任何包所使用的空间。'],
        'SET_PREFERRED_APPLICATIONS': ['signature', '设置首选应用程序', '允许应用程序修改您的首选应用程序。这可能允许恶意应用程序悄悄地更改正在运行的应用程序，欺骗您现有的应用程序以收集您的私人数据。'],
        'RECEIVE_BOOT_COMPLETED': ['normal', '开机自启动', '允许应用程序在系统完成启动后立即自行启动。这可能会导致启动手机的时间变长，并且应用程序会因始终运行而减慢整个手机的速度。'],
        'BROADCAST_STICKY': ['normal', '发送粘性广播', '允许应用程序发送粘性广播，这些广播在广播结束后仍然保留。恶意应用程序可能会导致手机使用过多内存，从而导致手机速度变慢或不稳定。'],
        'WAKE_LOCK': ['normal', '阻止手机休眠', '允许应用程序阻止手机进入睡眠状态。'],
        'SET_WALLPAPER': ['normal', '设置壁纸', '允许应用程序设置系统壁纸。'],
        'SET_WALLPAPER_HINTS': ['normal', '设置壁纸尺寸提示', '允许应用程序设置系统壁纸尺寸提示。'],
        'SET_TIME': ['signatureOrSystem', '设置时间', '允许应用程序改变手机时钟时间。'],
        'SET_TIME_ZONE': ['signatureOrSystem', '设置时区', '允许应用程序更改手机的时区。'],
        'MOUNT_UNMOUNT_FILESYSTEMS': ['dangerous', '挂载和卸载文件系统', '允许应用程序挂载和卸载可移动存储的文件系统。'],
        'MOUNT_FORMAT_FILESYSTEMS': ['dangerous', '格式化外部存储', '允许应用程序格式化可移动存储。'],
        'ASEC_ACCESS': ['signature', '获取内部存储信息', '允许应用程序获取有关内部存储的信息。'],
        'ASEC_CREATE': ['signature', '创建内部存储', '允许应用程序创建内部存储。'],
        'ASEC_DESTROY': ['signature', '破坏内部存储', '允许应用程序破坏内部存储。'],
        'ASEC_MOUNT_UNMOUNT': ['signature', '安装/卸载内部存储', '允许应用程序安装/卸载内部存储。'],
        'ASEC_RENAME': ['signature', '重命名内部存储', '允许应用程序重命名内部存储。'],
        'DISABLE_KEYGUARD': ['normal', '禁用键盘保护', '如果键盘保护不安全，则允许应用程序禁用它。'],
        'READ_SYNC_SETTINGS': ['normal', '读取同步设置', '允许应用程序读取同步设置，例如是否为联系人启用同步。'],
        'WRITE_SYNC_SETTINGS': ['normal', '写入同步设置', '允许应用程序修改同步设置，例如是否为联系人启用同步。'],
        'READ_SYNC_STATS': ['normal', '读取同步统计信息', '允许应用程序读取同步统计信息；例如已发生的同步历史记录。'],
        'WRITE_APN_SETTINGS': ['dangerous', '写入接入点名称设置', '允许应用程序修改 APN 设置，例如任何 APN 的代理和端口。'],
        'SUBSCRIBED_FEEDS_READ': ['normal', '读取同步源', '允许应用程序接收有关当前同步源的详细信息。'],
        'SUBSCRIBED_FEEDS_WRITE': ['dangerous', '写入同步源', '允许应用程序修改您当前同步的源。这可能允许恶意应用程序更改您的同步源。'],
        'CHANGE_NETWORK_STATE': ['normal', '更改网络连接', '允许应用程序更改网络连接状态。'],
        'CHANGE_WIFI_STATE': ['normal', '更改 Wi-Fi 状态', '允许应用程序连接到 Wi-Fi 接入点和断开连接，以及更改配置的 Wi-Fi 网络。'],
        'CHANGE_WIFI_MULTICAST_STATE': ['normal', '允许 Wi-Fi 组播接收', '允许应用程序接收未直接发送至您设备的数据包。这在发现附近提供的服务时非常有用。它比非多播模式消耗更多的电量。'],
        'BLUETOOTH_ADMIN': ['normal', '蓝牙管理', '允许应用程序发现并配对蓝牙设备。'],
        'CLEAR_APP_CACHE': ['signatureOrSystem', '删除所有应用程序缓存数据', '允许应用程序通过删除应用程序缓存目录中的文件来释放手机存储空间。访问通常非常限制于系统进程。'],
        'READ_LOGS': ['dangerous', '读取敏感日志数据', '允许应用程序读取系统的各种日志文件。这使得它能够发现有关您使用手机进行的操作的一般信息，可能包括个人或私人信息。'],
        'SET_DEBUG_APP': ['dangerous', '启用应用程序调试', '允许一个应用程序打开另一个应用程序的调试。恶意应用程序可以利用它来杀死其他应用程序。'],
        'SET_PROCESS_LIMIT': ['dangerous', '限制正在运行的进程数量', '允许应用程序控制将运行的最大进程数。普通应用程序不需要。'],
        'SET_ALWAYS_FINISH': ['dangerous', '关闭所有后台应用程序', '允许应用程序控制活动是否始终在进入后台后立即完成。普通应用程序不需要。'],
        'SIGNAL_PERSISTENT_PROCESSES': ['dangerous', '向应用程序发送 Linux 信号', '允许应用程序请求将提供的信号发送到所有持久进程。'],
        'DIAGNOSTIC': ['signature', '读/写诊断拥有的资源', '允许应用程序读取和写入诊断组拥有的任何资源；例如，/dev 中的文件。这可能会影响系统的稳定性和安全性。这只能用于制造商或运营商的硬件特定诊断。'],
        'STATUS_BAR': ['signatureOrSystem', '禁用或修改状态栏', '允许应用程序禁用状态栏或添加和删除系统图标。'],
        'STATUS_BAR_SERVICE': ['signature', '状态栏', '允许应用程序成为状态栏。'],
        'FORCE_BACK': ['signature', '强制应用程序关闭', '允许应用程序强制关闭并返回前台的任何活动。普通应用程序永远不需要它。'],
        'UPDATE_DEVICE_STATS': ['signatureOrSystem', '修改电池统计数据', '允许修改收集的电池统计信息。不适合普通应用程序使用。'],
        'INTERNAL_SYSTEM_WINDOW': ['signature', '显示未经授权的窗口', '允许创建供内部系统用户界面使用的窗口。不适合普通应用程序使用。'],
        'MANAGE_APP_TOKENS': ['signature', '管理应用程序令牌', '允许应用程序创建和管理自己的令牌，绕过其常见的 Z 排序。普通应用程序永远不需要它。'],
        'INJECT_EVENTS': ['signature', '按键和控制按钮', '允许应用程序将自己的输入事件（按键等）传递给其他应用程序。恶意应用程序可以利用它来接管手机。'],
        'SET_ACTIVITY_WATCHER': ['signature', '监视和控制所有应用程序启动', '允许应用程序监视和控制系统如何启动活动。恶意应用程序可能会完全破坏系统。仅开发需要此权限，普通手机使用不需要此权限。'],
        'SHUTDOWN': ['signature', '部分关闭', '将活动管理器置于关闭状态。不执行完全关闭。'],
        'STOP_APP_SWITCHES': ['signature', '阻止应用程序切换', '阻止用户切换到另一个应用程序。'],
        'READ_INPUT_STATE': ['signature', '记录您输入的内容和执行的操作', '即使在与其他应用程序交互（例如输入密码）时，也允许应用程序监视您按下的按键。普通应用程序永远不需要它。'],
        'BIND_INPUT_METHOD': ['signature', '绑定到输入法', '允许持有者绑定到输入法的顶层接口。普通应用程序永远不需要它。'],
        'BIND_WALLPAPER': ['signatureOrSystem', '绑定到壁纸', '允许持有者绑定到壁纸的顶层界面。普通应用程序永远不需要它。'],
        'BIND_DEVICE_ADMIN': ['signature', '与设备管理员交互', '允许持有者向设备管理员发送信息。普通应用程序永远不需要它。'],
        'SET_ORIENTATION': ['signature', '改变屏幕方向', '允许应用程序随时更改屏幕的旋转。普通应用程序永远不需要它。'],
        'INSTALL_PACKAGES': ['signatureOrSystem', '直接安装应用程序', '允许应用程序安装新的或更新的 Android 软件包。恶意应用程序可以利用它来添加具有任意强大权限的新应用程序。'],
        'REQUEST_INSTALL_PACKAGES': ['dangerous', '允许应用程序请求安装包', '恶意应用程序可以利用它来尝试诱骗用户安装其他恶意软件包。'],
        'CLEAR_APP_USER_DATA': ['signature', '删除其他应用程序的数据', '允许应用程序清除用户数据。'],
        'DELETE_CACHE_FILES': ['signatureOrSystem', '删除其他应用程序的缓存', '允许应用程序删除缓存文件。'],
        'DELETE_PACKAGES': ['signatureOrSystem', '删除应用程序', '允许应用程序删除 Android 包。恶意应用程序可以利用它来删除重要的应用程序。'],
        'MOVE_PACKAGE': ['signatureOrSystem', '移动应用程序资源', '允许应用程序将应用程序资源从内部媒体移动到外部媒体，反之亦然。'],
        'CHANGE_COMPONENT_ENABLED_STATE': ['signatureOrSystem', '启用或禁用应用程序组件', '允许应用程序更改是否启用另一个应用程序的组件。恶意应用程序可以利用它来禁用重要的手机功能。请务必小心权限，因为可能会使应用程序组件进入不可用、不一致或不稳定的状态。'],
        'ACCESS_SURFACE_FLINGER': ['signature', '访问SurfaceFlinger', '允许应用程序使用 SurfaceFlinger 低级功能。'],
        'READ_FRAME_BUFFER': ['signature', '读取帧缓冲区', '允许应用程序读取帧缓冲区的内容。'],
        'BRICK': ['signature', '永久禁用手机', '允许应用程序永久禁用整个手机。这是非常危险的。'],
        'REBOOT': ['signatureOrSystem', '强制手机重启', '允许应用程序强制手机重新启动。'],
        'DEVICE_POWER': ['signature', '打开或关闭手机', '允许应用程序打开或关闭手机。'],
        'FACTORY_TEST': ['signature', '在工厂测试模式下运行', '作为低级制造商测试运行，允许完全访问手机硬件。仅当手机在制造商测试模式下运行时才可用。'],
        'BROADCAST_PACKAGE_REMOVED': ['signature', '发送包删除广播', '允许应用程序广播应用程序包已被删除的通知。恶意应用程序可能会利用它来杀死任何其他正在运行的应用程序。'],
        'BROADCAST_SMS': ['signature', '发送短信收到的广播', '允许应用程序广播已收到 SMS 消息的通知。恶意应用程序可能会利用它来伪造传入的 SMS 消息。'],
        'BROADCAST_WAP_PUSH': ['signature', '发送 WAP-PUSH 收到的广播', '允许应用程序广播已收到 WAP-PUSH 消息的通知。恶意应用程序可能会利用这一点来伪造彩信收据或用恶意变体悄悄替换任何网页的内容。'],
        'MASTER_CLEAR': ['signatureOrSystem', '将系统重置为出厂默认设置', '允许应用程序将系统完全重置为出厂设置，删除所有数据、配置和已安装的应用程序。'],
        'CALL_PRIVILEGED': ['signatureOrSystem', '直接拨打任何电话号码', '允许应用程序拨打任何电话号码，包括紧急号码，而无需您的干预。恶意应用程序可能会向紧急服务机构发出不必要的非法呼叫。'],
        'PERFORM_CDMA_PROVISIONING': ['signatureOrSystem', '直接启动CDMA手机设置', '允许应用程序启动 CDMA 配置。恶意应用程序可能会不必要地启动 CDMA 配置。'],
        'CONTROL_LOCATION_UPDATES': ['signatureOrSystem', '控制位置更新通知', '允许从无线电中启用/禁用位置更新通知。不适用于常规应用程序。'],
        'ACCESS_CHECKIN_PROPERTIES': ['signatureOrSystem', '访问签到属性', '允许读取/写入由签到服务上传的属性。不适用于常规应用程序。'],
        'PACKAGE_USAGE_STATS': ['signature', '更新组件使用统计', '允许修改已收集的组件使用统计数据。不适用于常规应用程序。'],
        'BATTERY_STATS': ['signature', '修改电池统计', '允许修改已收集的电池统计数据。不适用于常规应用程序。'],
        'BACKUP': ['signatureOrSystem', '控制系统备份和恢复', '允许应用程序控制系统的备份和恢复机制。不适用于常规应用程序。'],
        'BIND_APPWIDGET': ['signatureOrSystem', '选择小部件', '允许应用程序告诉系统哪些小部件可以被哪些应用程序使用。有了此权限，应用程序可以将个人数据访问权限授予其他应用程序。不适用于常规应用程序。'],
        'CHANGE_BACKGROUND_DATA_SETTING': ['signature', '更改后台数据使用设置', '允许应用程序更改后台数据使用设置。'],
        'GLOBAL_SEARCH': ['signatureOrSystem', "允许全局搜索系统访问提供程序的数据", '此权限可用于内容提供程序，以允许全局搜索系统访问其数据。通常情况下，当提供程序有一些权限保护时（全局搜索不应该具有），会将其添加为只读权限到提供程序中执行全局搜索查询的路径上。这个权限不能由常规应用程序持有；它被应用程序用来保护自己免受除了全局搜索之外的所有其他人的影响。'],
        'GLOBAL_SEARCH_CONTROL': ['signature', '未指定角色或功能的权限', '未指定角色或功能的权限。'],
        'SET_WALLPAPER_COMPONENT': ['signatureOrSystem', '允许设置壁纸组件', '允许设置壁纸组件。'],
        'ACCESS_CACHE_FILESYSTEM': ['signatureOrSystem', '访问缓存文件系统', '允许应用程序读取和写入缓存文件系统。'],
        'COPY_PROTECTED_DATA': ['signature', '允许调用默认容器服务复制内容。不适用于常规应用程序', '允许调用默认容器服务复制内容。不适用于常规应用程序。'],
        'C2D_MESSAGE': ['signature', '允许云到设备消息', '允许应用程序接收推送通知。'],
        'ADD_VOICEMAIL': ['dangerous', '将语音邮件添加到系统中', '允许应用程序将语音邮件添加到系统中。'],
        'ACCEPT_HANDOVER': ['dangerous', '使调用应用程序能够继续在另一个应用程序中启动的通话', '允许调用应用程序继续在另一个应用程序中启动的通话。例如，视频通话应用程序希望在用户的移动网络上继续语音通话。'],
        'ACCESS_NOTIFICATION_POLICY': ['normal', '用于访问通知策略的标记权限', '用于希望访问通知策略的应用程序的标记权限。'],
        'ANSWER_PHONE_CALLS': ['dangerous', '允许应用程序接听来电', '允许应用程序接听来电。'],
        'BIND_ACCESSIBILITY_SERVICE': ['signature', 'AccessibilityServices所需的系统绑定权限', '必须由AccessibilityService所需，以确保只有系统可以绑定到它。'],
        'BIND_AUTOFILL_SERVICE': ['signature', 'AutofillServices所需的系统绑定权限', '必须由AutofillService所需，以确保只有系统可以绑定到它。'],
        'BIND_CARRIER_MESSAGING_SERVICE': ['signature', '用于绑定到载体消息服务的系统级权限', '被允许绑定到载体应用程序中的服务的系统进程将具有此权限。'],
        'BIND_CARRIER_SERVICES': ['signature', '用于绑定到载体服务的系统级权限', '被允许绑定到载体应用程序中的服务的系统进程将具有此权限。载体应用程序应使用此权限来保护只有系统允许绑定到的服务。'],
        'BIND_CHOOSER_TARGET_SERVICE': ['signature', 'ChooserTargetServices所需的系统绑定权限', '必须由ChooserTargetService所需，以确保只有系统可以绑定到它。'],
        'BIND_CONDITION_PROVIDER_SERVICE': ['signature', 'ConditionProviderServices所需的系统绑定权限', '必须由ConditionProviderService所需，以确保只有系统可以绑定到它。'],
        'BIND_DREAM_SERVICE': ['signature', 'DreamServices所需的系统绑定权限', '必须由DreamService所需，以确保只有系统可以绑定到它。'],
        'BIND_INCALL_SERVICE': ['signature', 'InCallServices所需的系统绑定权限', '必须由InCallService所需，以确保只有系统可以绑定到它。'],
        'BIND_MIDI_DEVICE_SERVICE': ['signature', 'MidiDeviceServices所需的系统绑定权限', '必须由MidiDeviceService所需，以确保只有系统可以绑定到它。'],
        'BIND_NFC_SERVICE': ['signature', '用于绑定到NFC服务的系统绑定权限', '必须由HostApduService或OffHostApduService所需，以确保只有系统可以绑定到它。'],
        'BIND_NOTIFICATION_LISTENER_SERVICE': ['signature', 'NotificationListenerServices所需的系统绑定权限', '必须由NotificationListenerService所需，以确保只有系统可以绑定到它。'],
        'BIND_PRINT_SERVICE': ['signature', '打印服务所需的权限', '必须由PrintService所需，以确保只有系统可以绑定到它。'],
        'BIND_QUICK_SETTINGS_TILE': ['signatureOrSystem', '允许绑定第三方快速设置磁贴', '允许应用程序绑定第三方快速设置磁贴。'],
        'BIND_REMOTEVIEWS': ['signature', 'RemoteViewsServices所需的系统绑定权限', '必须由RemoteViewsService所需，以确保只有系统可以绑定到它。'],
        'BIND_SCREENING_SERVICE': ['signature', 'CallScreeningServices所需的系统绑定权限', '必须由CallScreeningService所需，以确保只有系统可以绑定到它。'],
        'BIND_TELECOM_CONNECTION_SERVICE': ['signature', 'ConnectionServices所需的系统绑定权限', '必须由ConnectionService所需，以确保只有系统可以绑定到它。'],
        'BIND_TEXT_SERVICE': ['signature', 'TextServices（例如，SpellCheckerService）所需的系统绑定权限', '必须由TextService（例如，SpellCheckerService）所需，以确保只有系统可以绑定到它。'],
        'BIND_TV_INPUT': ['signature', 'TvInputServices所需的系统绑定权限', '必须由TvInputService所需，以确保只有系统可以绑定到它。'],
        'BIND_VISUAL_VOICEMAIL_SERVICE': ['signature', 'VisualVoicemailServices所需的系统绑定权限', '必须由VisualVoicemailService所需，以确保只有系统可以绑定到它。'],
        'BIND_VOICE_INTERACTION': ['signature', 'VoiceInteractionServices所需的系统绑定权限', '必须由VoiceInteractionService所需，以确保只有系统可以绑定到它。'],
        'BIND_VPN_SERVICE': ['signature', 'VpnServices所需的系统绑定权限', '必须由VpnService所需，以确保只有系统可以绑定到它。'],
        'BIND_VR_LISTENER_SERVICE': ['signature', 'VrListenerServices所需的系统绑定权限', '必须由VrListenerService所需，以确保只有系统可以绑定到它。'],
        'BLUETOOTH_PRIVILEGED': ['signatureOrSystem', '允许特权蓝牙操作而无需用户交互', '允许应用程序在无需用户交互的情况下对蓝牙设备进行配对，并允许或禁止电话簿访问或消息访问。这不适用于第三方应用程序。'],
        'BODY_SENSORS': ['dangerous', '授予对身体传感器的访问权限，例如心率', '允许应用程序访问用户用于测量身体内部发生情况的传感器数据，例如心率。'],
        'CAPTURE_AUDIO_OUTPUT': ['signatureOrSystem', '允许捕获音频输出', '允许应用程序捕获音频输出。'],
        'CAPTURE_SECURE_VIDEO_OUTPUT': ['normal', '允许捕获安全视频输出', '允许应用程序捕获安全视频输出。'],
        'CAPTURE_VIDEO_OUTPUT': ['normal', '允许捕获视频输出', '允许应用程序捕获视频输出。'],
        'FOREGROUND_SERVICE': ['normal', '使常规应用程序可以使用Service.startForeground', '允许常规应用程序使用Service.startForeground。'],
        'GET_ACCOUNTS_PRIVILEGED': ['signatureOrSystem', '授予对帐户服务的访问权限', '允许访问帐户服务中的帐户列表。'],
        'INSTALL_SHORTCUT': ['normal', '允许在启动器中安装快捷方式', '允许应用程序在启动器中安装快捷方式。'],
        'INSTANT_APP_FOREGROUND_SERVICE': ['signatureOrSystem', '允许即时应用程序创建前台服务', '允许即时应用程序创建前台服务。'],
        'LOCATION_HARDWARE': ['normal', '允许在硬件中使用位置功能', '允许应用程序在硬件中使用位置功能，例如地理围栏API。'],
        'MANAGE_DOCUMENTS': ['signature', '允许管理文档访问，通常在选择器中', '允许应用程序管理对文档的访问，通常作为文档选择器的一部分。'],
        'MANAGE_OWN_CALLS': ['normal', '使调用应用程序可以管理其自己的通话', '允许通过自管理的ConnectionService API管理自己的通话的调用应用程序。'],
        'MEDIA_CONTENT_CONTROL': ['normal', '允许对媒体内容播放进行控制', '允许应用程序知道正在播放的内容并控制其播放。'],
        'NFC_TRANSACTION_EVENT': ['normal', '允许接收NFC事务事件', '允许应用程序接收NFC事务事件。'],
        'READ_CALL_LOG': ['dangerous', '授予对用户通话记录的读取访问权限', '允许应用程序读取用户的通话记录。'],
        'READ_PHONE_NUMBERS': ['dangerous', '允许读取设备的电话号码', '允许读取设备的电话号码。这是READ_PHONE_STATE授予权限的一个子集，但暴露给即时应用程序。'],
        'READ_VOICEMAIL': ['signature', '允许应用程序读取系统中的语音邮件', '允许应用程序读取系统中的语音邮件。'],
        'REQUEST_COMPANION_RUN_IN_BACKGROUND': ['normal', '允许伴随应用在后台运行', '允许伴随应用在后台运行。'],
        'REQUEST_COMPANION_USE_DATA_IN_BACKGROUND': ['normal', '允许伴随应用在后台使用数据', '允许伴随应用在后台使用数据。'],
        'REQUEST_DELETE_PACKAGES': ['normal', '允许应用请求删除软件包', '允许应用请求删除软件包。'],
        'REQUEST_IGNORE_BATTERY_OPTIMIZATIONS': ['normal', '用于使用Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS的权限', '应用程序必须持有的权限，以便使用Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS。'],
        'SEND_RESPOND_VIA_MESSAGE': ['signatureOrSystem', '允许在通话期间发送应答消息请求。', '允许应用程序（电话）向其他应用程序发送请求，以处理通话期间的应答消息操作。'],
        'TRANSMIT_IR': ['normal', '启用设备的红外发射器', '如果可用，允许使用设备的红外发射器。'],
        'UNINSTALL_SHORTCUT': ['normal', '卸载快捷方式的已弃用权限', '请勿在应用中使用此权限。此权限不再受支持。'],
        'USE_BIOMETRIC': ['normal', '允许使用设备支持的生物识别模式', '允许应用程序使用设备支持的生物识别模式。'],
        'USE_FINGERPRINT': ['normal', '允许使用指纹', '此常量在 API 级别 28 中已弃用。应用程序应改为请求USE_BIOMETRIC。'],
        'WRITE_CALL_LOG': ['dangerous', '允许写入（但不读取）用户的通话记录', '允许应用程序写入（但不读取）用户的通话记录数据。'],
        'WRITE_VOICEMAIL': ['signature', '允许修改和删除语音邮件', '允许应用程序修改和删除系统中的现有语音邮件。'],
        'ACCESS_BACKGROUND_LOCATION': ['dangerous', '后台访问位置', '允许应用程序在后台访问位置。'],
        'ACCESS_MEDIA_LOCATION': ['dangerous', '访问任何地理位置', '允许应用程序访问用户的共享集合中持久保存的任何地理位置。'],
        'ACTIVITY_RECOGNITION': ['dangerous', '允许应用程序识别物理活动', '允许应用程序识别物理活动。'],
        'BIND_CALL_REDIRECTION_SERVICE': ['signature', 'CallRedirectionServices所需的系统绑定权限', '必须由CallRedirectionService所需，以确保只有系统可以绑定到它。'],
        'BIND_CARRIER_MESSAGING_CLIENT_SERVICE': ['signature', 'CarrierMessagingClientServices所需的系统保护权限', 'CarrierMessagingClientService的子类必须受到此权限的保护。'],
        'CALL_COMPANION_APP': ['normal', '使InCallService应用程序能够作为呼叫伴侣运行', '允许实现InCallService API的应用程序有资格启用为呼叫伴侣应用程序。这意味着当有活动呼叫时，电信框架将绑定到应用程序的InCallService实现。应用程序可以使用InCallService API查看系统上的呼叫信息并控制这些呼叫。'],
        'REQUEST_PASSWORD_COMPLEXITY': ['normal', '允许请求和提示屏幕锁定复杂性升级', '允许应用程序请求屏幕锁定复杂性并提示用户将屏幕锁定更新为特定复杂性级别。'],
        'SMS_FINANCIAL_TRANSACTIONS': ['signature', '允许金融应用程序读取过滤的短信消息', '允许金融应用程序读取过滤的短信消息。保护级别：signature|appop。此常量在API级别S中已弃用。'],
        'START_VIEW_PERMISSION_USAGE': ['signature', '允许启动应用程序的权限使用屏幕', '允许持有者启动应用程序的权限使用屏幕。'],
        'USE_FULL_SCREEN_INTENT': ['normal', '用于通知中的全屏意图', '适用于目标为Build.VERSION_CODES.Q的应用程序，希望使用通知全屏意图。'],
        'ACCESS_CALL_AUDIO': ['signature', '应用程序可以访问通话音频', '允许分配给拨号器角色的应用程序访问电话呼叫音频流，包括TX和RX。'],
        'BIND_CONTROLS': ['signatureOrSystem', '允许SystemUI请求第三方控件', '允许SystemUI请求第三方控件。应该只由系统请求并由ControlsProviderService声明所需。'],
        'BIND_QUICK_ACCESS_WALLET_SERVICE': ['signature', 'QuickAccessWalletServices所需的系统绑定权限', '必须由QuickAccessWalletService所需，以确保只有系统可以绑定到它。'],
        'INTERACT_ACROSS_PROFILES': ['normal', '在同一组中跨档案进行交互', '允许在同一档案组中的档案之间进行交互。'],
        'LOADER_USAGE_STATS': ['signatureOrSystem', '允许数据加载器读取软件包访问日志', '允许数据加载器读取软件包的访问日志。访问日志包含随时间引用的页面集。'],
        'MANAGE_EXTERNAL_STORAGE': ['dangerous', '允许应用程序在作用域存储中广泛访问外部存储', '允许应用程序在作用域存储中广泛访问外部存储。预期用于需要代表用户管理文件的少数应用程序。'],
        'NFC_PREFERRED_PAYMENT_INFO': ['normal', '允许接收NFC首选付款服务信息', '允许应用程序接收NFC首选付款服务信息。'],
        'QUERY_ALL_PACKAGES': ['normal', '允许查询设备上的任何普通应用程序', '允许查询设备上的任何普通应用程序，而不考虑清单声明。'],
        'READ_PRECISE_PHONE_STATE': ['dangerous', '允许查询设备上的任何普通应用程序', '允许查询设备上的任何普通应用程序，而不考虑清单声明。'],
        'READ_APP_BADGE': ['normal', '显示应用通知', '允许应用程序显示应用程序图标徽章。'],
        'BIND_COMPANION_DEVICE_SERVICE': ['normal', 'CompanionDeviceServices所需的系统绑定权限', '必须由任何CompanionDeviceServices所需，以确保只有系统可以绑定到它。'],
        'HIDE_OVERLAY_WINDOWS': ['normal', '阻止绘制非系统叠加窗口', '允许应用程序防止绘制在其上面的非系统叠加窗口。'],
        'HIGH_SAMPLING_RATE_SENSORS': ['normal', '访问高采样率传感器数据', '允许应用程序访问采样率大于200 Hz的传感器数据。'],
        'MANAGE_ONGOING_CALLS': ['signature', '查询和管理正在进行的通话详细信息', '允许查询正在进行的通话详细信息并管理正在进行的通话。'],
        'REQUEST_COMPANION_PROFILE_WATCH': ['normal', '使应用程序能够作为"手表"与设备关联', '允许应用程序通过CompanionDeviceManager请求将其关联到设备作为"手表"。'],
        'REQUEST_OBSERVE_COMPANION_DEVICE_PRESENCE': ['normal', '允许订阅伴侣设备存在状态通知', '允许应用程序订阅有关其关联伴侣设备的存在状态更改的通知。'],
        'SCHEDULE_EXACT_ALARM': ['normal', '允许后台工作的精确闹钟调度', '允许应用程序使用精确闹钟调度API执行时间敏感的后台工作。'],
        'USE_ICC_AUTH_WITH_DEVICE_IDENTIFIER': ['signature', '允许读取设备标识符并使用基于ICC的身份验证', '允许读取设备标识符并使用基于ICC的身份验证，如EAP-AKA。在访问运营商服务器并管理订户服务的身份验证中通常需要。'],
        'ACCESS_BLOBS_ACROSS_USERS': ['normal', '允许跨用户访问数据blob', '允许应用程序跨用户访问数据blob。'],
        'BIND_CREDENTIAL_PROVIDER_SERVICE': ['signature', 'CredentialProviderServices所需的系统绑定权限', '必须由CredentialProviderService所需，以确保只有系统可以绑定到它。'],
        'BIND_TV_INTERACTIVE_APP': ['signature', 'TvInteractiveAppServices所需的系统绑定权限', '必须由TvInteractiveAppService所需，以确保只有系统可以绑定到它。'],
        'BLUETOOTH_ADVERTISE': ['dangerous', '允许向附近的蓝牙设备广告', '允许能够向附近的蓝牙设备进行广告。'],
        'BLUETOOTH_CONNECT': ['dangerous', 'dangerous', '连接到配对的蓝牙设备所需', '允许能够连接到配对的蓝牙设备。'],
        'BLUETOOTH_SCAN': ['dangerous', '发现和配对蓝牙设备所需', '允许能够发现和配对附近的蓝牙设备。'],
        'BODY_SENSORS_BACKGROUND': ['dangerous', '后台访问身体传感器，如心率', '允许应用程序在后台访问用户用于测量身体内部发生情况的传感器数据，如心率。如果您正在请求此权限，则还必须请求BODY_SENSORS。仅请求此权限本身不会给您Body sensors访问权限。'],
        'CONFIGURE_WIFI_DISPLAY': ['normal', '允许配置和连接到Wifi显示器', '允许应用程序配置和连接到Wifi显示器。'],
        'CREDENTIAL_MANAGER_QUERY_CANDIDATE_CREDENTIALS': ['normal', '允许查询凭据候选项的元数据', '允许浏览器调用一组查询API以获取凭据管理器准备的凭据候选项的元数据。'],
        'CREDENTIAL_MANAGER_SET_ALLOWED_PROVIDERS': ['normal', '允许指定候选凭据提供程序', '允许在凭据管理器get流中指定候选凭据提供程序以进行查询，或在凭据管理器create流中作为默认提供程序。'],
        'CREDENTIAL_MANAGER_SET_ORIGIN': ['normal', '允许代表另一个RP启用凭据管理器API', '允许浏览器代表另一个RP调用凭据管理器API。'],
        'DELIVER_COMPANION_MESSAGES': ['normal', '允许将伴侣消息传递给系统', '允许应用程序将伴侣消息传递给系统。'],
        'DETECT_SCREEN_CAPTURE': ['normal', '尝试捕获应用程序窗口的屏幕截图时发出通知', '允许应用程序在尝试捕获其窗口的屏幕截图时收到通知。'],
        'ENFORCE_UPDATE_OWNERSHIP': ['normal', '指示通过PackageInstaller成为更新所有者的意图', '允许应用程序通过PackageInstaller.SessionParams.setRequestUpdateOwnership(boolean)指示其有成为更新所有者的意图。'],
        'EXECUTE_APP_ACTION': ['internal', '允许辅助应用程序在其他应用程序内执行操作', '允许辅助应用程序代表用户在应用程序内执行操作。'],
        'FOREGROUND_SERVICE_CAMERA': ['normal', '允许具有相机使用的前台服务', '允许常规应用程序使用类型为“camera”的Service.startForeground。'],
        'FOREGROUND_SERVICE_CONNECTED_DEVICE': ['normal', '允许连接设备使用的前台服务', '允许常规应用程序使用类型为“connectedDevice”的Service.startForeground。'],
        'FOREGROUND_SERVICE_DATA_SYNC': ['normal', '允许数据同步的前台服务', '允许常规应用程序使用类型为“dataSync”的Service.startForeground。'],
        'FOREGROUND_SERVICE_HEALTH': ['normal', '允许具有与健康相关功能的前台服务', '允许常规应用程序使用类型为“health”的Service.startForeground。'],
        'FOREGROUND_SERVICE_LOCATION': ['normal', '允许位置使用的前台服务', '允许常规应用程序使用类型为“location”的Service.startForeground。'],
        'FOREGROUND_SERVICE_MEDIA_PLAYBACK': ['normal', '允许媒体播放的前台服务', '允许常规应用程序使用类型为“mediaPlayback”的Service.startForeground。'],
        'FOREGROUND_SERVICE_MEDIA_PROJECTION': ['normal', '允许媒体投影的前台服务', '允许常规应用程序使用类型为“mediaProjection”的Service.startForeground。'],
        'FOREGROUND_SERVICE_MICROPHONE': ['normal', '允许使用麦克风的前台服务', '允许常规应用程序使用类型为“microphone”的Service.startForeground。'],
        'FOREGROUND_SERVICE_PHONE_CALL': ['normal', '允许通话期间的前台服务', '允许常规应用程序使用类型为“phoneCall”的Service.startForeground。'],
        'FOREGROUND_SERVICE_REMOTE_MESSAGING': ['normal', '允许远程消息的前台服务', '允许常规应用程序使用类型为“remoteMessaging”的Service.startForeground。'],
        'FOREGROUND_SERVICE_SPECIAL_USE': ['normal', '允许特殊用途的前台服务', '允许常规应用程序使用类型为“specialUse”的Service.startForeground。'],
        'FOREGROUND_SERVICE_SYSTEM_EXEMPTED': ['normal', '允许系统豁免类型的前台服务', '允许常规应用程序使用类型为“systemExempted”的Service.startForeground。仅允许应用程序在ServiceInfo.FOREGROUND_SERVICE_TYPE_SYSTEM_EXEMPTED中列出的用例中使用此类型。'],
        'LAUNCH_CAPTURE_CONTENT_ACTIVITY_FOR_NOTE': ['internal', '启用屏幕内容捕获以进行截图', '允许应用程序使用意图操作 Intent.ACTION_LAUNCH_CAPTURE_CONTENT_ACTIVITY_FOR_NOTE 捕获屏幕内容以执行截图。'],
        'LAUNCH_MULTI_PANE_SETTINGS_DEEP_LINK': ['normal', '启用在设置应用程序中嵌入活动', '应用程序需要此权限以显示其活动嵌入在设置应用程序中的 Settings.ACTION_SETTINGS_EMBED_DEEP_LINK_ACTIVITY。'],
        'MANAGE_DEVICE_LOCK_STATE': ['internal', '允许融资的设备亭应用程序与设备锁定服务进行交互', '允许融资的设备亭应用程序对设备锁定服务执行操作。'],
        'MANAGE_DEVICE_POLICY_ACCESSIBILITY': ['normal', '启用管理与辅助功能相关的策略', '允许应用程序管理与辅助功能相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 来调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_ACCOUNT_MANAGEMENT': ['normal', '允许设置与帐户管理相关的策略', '允许应用程序设置与帐户管理相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS 来调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_ACROSS_USERS': ['normal', '启用在不访问用户数据的情况下设置安全设备策略', '允许应用程序在不访问用户数据的情况下设置当前用户之外的设备策略，这是为了确保设备所有权的安全。持有此权限允许在设备上的所有用户之间使用其他已持有的 MANAGE_DEVICE_POLICY_* 权限，前提是它们不授予对用户数据的访问权限。'],
        'MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL': ['normal', '允许设置具有访问用户数据权限的设备策略', '允许应用程序在当前用户之外设置设备策略。MANAGE_DEVICE_POLICY_ACROSS_USERS 的更完整形式，取消了对访问用户数据的限制。持有此权限允许在设备上的所有用户之间使用任何其他已持有的 MANAGE_DEVICE_POLICY_* 权限。常量值："android.permission.MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL"'],
        'MANAGE_DEVICE_POLICY_ACROSS_USERS_SECURITY_CRITICAL': ['normal', '启用关键的安全策略，用于保护用户数据', '允许应用程序在当前用户之外设置关键的安全策略，这些策略对于保护当前用户的数据至关重要。持有此权限允许在设备上的所有用户之间使用其他已持有的 MANAGE_DEVICE_POLICY_* 权限，前提是这些策略对于保护当前用户的数据是必要的。'],
        'MANAGE_DEVICE_POLICY_AIRPLANE_MODE': ['normal', '允许设置与飞行模式相关的策略', '允许应用程序设置与飞行模式相关的策略。Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS 权限是调用受此权限保护的与调用用户不同的用户的 API 所需的。'],
        'MANAGE_DEVICE_POLICY_APPS_CONTROL': ['normal', '允许管理修改应用程序的策略', '允许应用程序管理修改应用程序的策略。Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限是调用受此权限保护的与调用用户不同的用户的 API 所需的。'],
        'MANAGE_DEVICE_POLICY_APP_RESTRICTIONS': ['normal', '启用管理应用程序限制的策略', '允许应用程序管理应用程序限制。Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限是调用受此权限保护的与调用用户不同的用户的 API 所需的。'],
        'MANAGE_DEVICE_POLICY_APP_USER_DATA': ['normal', '允许设置与应用程序用户数据相关的策略', '允许应用程序管理与应用程序用户数据相关的策略。Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限是调用受此权限保护的与调用用户不同的用户的 API 所需的。'],
        'MANAGE_DEVICE_POLICY_AUDIO_OUTPUT': ['normal', '启用设置音频输出的策略', '允许应用程序设置与音频输出相关的策略。Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限是调用受此权限保护的与调用用户不同的用户的 API 所需的。'],
        'MANAGE_DEVICE_POLICY_AUTOFILL': ['normal', '允许设置自动填充服务的策略', '允许应用程序设置与自动填充相关的策略。Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限是调用受此权限保护的与调用用户不同的用户的 API 所需的。'],
        'MANAGE_DEVICE_POLICY_BACKUP_SERVICE': ['normal', '启用管理备份服务策略', '允许应用程序管理备份服务策略。Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限是调用受此权限保护的与调用用户不同的用户的 API 所需的。'],
        'MANAGE_DEVICE_POLICY_BLUETOOTH': ['normal', '允许设置与蓝牙相关的策略', '允许应用程序设置与蓝牙相关的策略。Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限是调用受此权限保护的与调用用户不同的用户的 API 所需的。'],
        'MANAGE_DEVICE_POLICY_BUGREPORT': ['normal', '允许请求用户同意的 bug 报告', '允许应用程序请求用户同意的 bug 报告。Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限是调用受此权限保护的与调用用户不同的用户的 API 所需的。'],
        'MANAGE_DEVICE_POLICY_CALLS': ['normal', '启用管理电话策略', '允许应用程序管理呼叫策略。Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限是调用受此权限保护的与调用用户不同的用户的 API 所需的。'],
        'MANAGE_DEVICE_POLICY_CAMERA': ['normal', '允许设置相机使用策略', '允许应用程序设置与限制用户使用、启用和禁用相机相关的策略。Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS 权限是调用受此权限保护的与调用用户不同的用户的 API 所需的。'],
        'MANAGE_DEVICE_POLICY_CERTIFICATES': ['normal', '允许证书策略管理', '允许应用程序设置与证书相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_COMMON_CRITERIA_MODE': ['normal', '启用通用标准模式的策略管理', '允许应用程序管理与通用标准模式相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_DEBUGGING_FEATURES': ['normal', '允许管理调试功能的策略', '允许应用程序管理调试功能策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_DEFAULT_SMS': ['normal', '允许设置默认短信应用程序的策略', '允许应用程序设置与默认短信应用程序相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS 权限。'],
        'MANAGE_DEVICE_POLICY_DEVICE_IDENTIFIERS': ['normal', '启用设备标识符的策略管理', '允许应用程序管理与设备标识符相关的策略。'],
        'MANAGE_DEVICE_POLICY_DISPLAY': ['normal', '允许设置显示管理策略', '允许应用程序设置与显示相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_FACTORY_RESET': ['normal', '启用恢复出厂设置的策略管理', '允许应用程序设置与恢复出厂设置相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_FUN': ['normal', '允许设置与有趣活动相关的策略', '允许应用程序设置与有趣活动相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_INPUT_METHODS': ['normal', '允许设置输入法的策略', '允许应用程序设置与输入法相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS 权限。'],
        'MANAGE_DEVICE_POLICY_INSTALL_UNKNOWN_SOURCES': ['normal', '启用从未知来源安装应用程序的策略', '允许应用程序管理从未知来源安装的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 MANAGE_SECURITY_CRITICAL_DEVICE_POLICY_ACROSS_USERS 权限。'],
        'MANAGE_DEVICE_POLICY_KEEP_UNINSTALLED_PACKAGES': ['normal', '允许根据策略保留未安装的应用程序包', '允许应用程序设置与保留未安装的应用程序包相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_KEYGUARD': ['normal', '启用键盘锁设置的策略管理', '允许应用程序管理与键盘锁相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_SECURITY_CRITICAL 权限。'],
        'MANAGE_DEVICE_POLICY_LOCALE': ['normal', '允许设置区域设置管理策略', '允许应用程序设置与区域设置相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_LOCATION': ['normal', '启用位置服务的策略设置', '允许应用程序设置与位置相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_LOCK': ['normal', '允许根据策略锁定配置文件或设备', '允许应用程序使用适当的跨用户权限锁定配置文件或设备。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_LOCK_CREDENTIALS': ['normal', '启用锁定凭据的策略设置', '允许应用程序设置与锁定凭据相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_SECURITY_CRITICAL 权限。'],
        'MANAGE_DEVICE_POLICY_LOCK_TASK': ['normal', '允许管理锁定任务策略', '允许应用程序管理锁定任务策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_METERED_DATA': ['normal', '允许管理计量数据策略', '允许应用程序管理与计量数据相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_MICROPHONE': ['normal', '允许设置麦克风使用策略', '允许应用程序设置与限制用户使用、启用和禁用麦克风相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS 权限。'],
        'MANAGE_DEVICE_POLICY_MOBILE_NETWORK': ['normal', '启用移动网络策略设置', '允许应用程序设置与移动网络相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_MODIFY_USERS': ['normal', '允许管理用户修改策略', '允许应用程序管理防止用户修改用户的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_MTE': ['normal', '启用内存标记扩展的策略管理', '允许应用程序管理与内存标记扩展（MTE）相关的策略。'],
        'MANAGE_DEVICE_POLICY_NEARBY_COMMUNICATION': ['normal', '允许设置附近通信策略', '允许应用程序设置与附近通信（例如 Beam 和附近流媒体）相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_NETWORK_LOGGING': ['normal', '启用网络日志记录策略设置', '允许应用程序设置与网络日志记录相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_ORGANIZATION_IDENTITY': ['normal', '允许管理组织标识的策略', '允许应用程序管理管理组织标识的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_OVERRIDE_APN': ['normal', '允许设置覆盖 APN 的策略', '允许应用程序设置与覆盖 APN 相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_PACKAGE_STATE': ['normal', '启用隐藏和挂起包的策略设置', '允许应用程序设置与隐藏和挂起包相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS 权限。'],
        'MANAGE_DEVICE_POLICY_PHYSICAL_MEDIA': ['normal', '允许设置物理介质使用策略', '允许应用程序设置与物理介质相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_PRINTING': ['normal', '允许设置打印服务策略', '允许应用程序设置与打印相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_PRIVATE_DNS': ['normal', '允许设置私有 DNS 管理策略', '允许应用程序设置与私有 DNS 相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_PROFILES': ['normal', '允许设置用户配置文件策略', '允许应用程序设置与配置文件相关的策略。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_PROFILE_INTERACTION': ['normal', '允许设置用户配置文件之间的交互策略', '允许应用程序设置与与配置文件交互相关的策略（例如，禁止跨配置文件复制和粘贴）。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_PROXY': ['normal', '允许独立于网络设置全局 HTTP 代理', '允许应用程序设置与网络无关的全局 HTTP 代理。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_QUERY_SYSTEM_UPDATES': ['normal', '允许查询系统更新', '允许应用程序查询系统更新。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_RESET_PASSWORD': ['normal', '允许强制设置新的设备解锁密码或配置文件挑战', '允许应用程序在当前用户上强制设置新的设备解锁密码或受管配置文件挑战。调用受此权限保护的与调用用户不同的用户的 API 需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限。'],
        'MANAGE_DEVICE_POLICY_RESTRICT_PRIVATE_DNS': ['normal', '允许限制用户配置私有 DNS', '允许应用程序设置限制用户配置私有 DNS 的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_RUNTIME_PERMISSIONS': ['normal', '允许为包设置运行时权限', '允许应用程序在包上设置运行时权限的授予状态。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_RUN_IN_BACKGROUND': ['normal', '允许设置后台进程管理策略', '允许应用程序设置与用户在后台运行相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_SAFE_BOOT': ['normal', '允许管理安全启动模式的策略', '允许应用程序管理安全启动策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_SCREEN_CAPTURE': ['normal', '允许设置屏幕捕获功能的策略', '允许应用程序设置与屏幕捕获相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_SCREEN_CONTENT': ['normal', '允许设置屏幕内容使用策略', '允许应用程序设置与屏幕内容使用相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_SECURITY_LOGGING': ['normal', '允许设置安全日志记录策略', '允许应用程序设置与安全日志记录相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_SETTINGS': ['normal', '允许设置通用设备策略', '允许应用程序设置与设置相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限以调用受此权限保护的不同于调用用户的用户的 API。.'],
        'MANAGE_DEVICE_POLICY_SMS': ['normal', '允许设置短信功能的策略', '允许应用程序设置与短信相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_STATUS_BAR': ['normal', '允许设置状态栏的策略', '允许应用程序设置与状态栏相关的策略'],
        'MANAGE_DEVICE_POLICY_SUPPORT_MESSAGE': ['normal', '允许为受策略影响的操作设置支持消息', '允许应用程序为用户操作受到活动策略影响时设置支持消息。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_SUSPEND_PERSONAL_APPS': ['normal', '允许通过策略设置暂停个人应用程序', '允许应用程序设置与暂停个人应用程序相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_SYSTEM_APPS': ['normal', '允许管理与系统应用程序相关的策略', '允许应用程序管理与系统应用程序相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_SYSTEM_DIALOGS': ['normal', '允许设置系统对话框的策略', '允许应用程序设置与系统对话框相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_SYSTEM_UPDATES': ['normal', '允许设置系统更新的策略', '允许应用程序设置与系统更新相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_TIME': ['normal', '允许管理与时间设置相关的策略', '允许应用程序管理与时间设置相关的设备策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_USB_DATA_SIGNALLING': ['normal', '允许设置 USB 数据信号的策略', '允许应用程序设置与 USB 数据信号相关的策略。'],
        'MANAGE_DEVICE_POLICY_USB_FILE_TRANSFER': ['normal', '允许设置 USB 文件传输的策略', '允许应用程序设置与 USB 文件传输相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_USERS': ['normal', '允许设置与用户管理相关的策略', '允许应用程序设置与用户相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限以调用受此权限保护的不同于调用用户的用户的 API。.'],
        'MANAGE_DEVICE_POLICY_VPN': ['normal', '允许设置 VPN 使用的策略', '允许应用程序设置与 VPN 相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_WALLPAPER': ['normal', '允许设置壁纸管理的策略', '允许应用程序设置与壁纸相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_WIFI': ['normal', '允许设置 WiFi 连接的策略', '允许应用程序设置与 WiFi 相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_WINDOWS': ['normal', '允许设置窗口管理的策略', '允许应用程序设置与窗口相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_DEVICE_POLICY_WIPE_DATA': ['normal', '允许管理数据擦除的策略', '允许应用程序管理与数据擦除相关的策略。需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS 权限以调用受此权限保护的不同于调用用户的用户的 API。'],
        'MANAGE_MEDIA': ['signature', '允许修改和删除媒体文件而无需用户确认', '允许应用程序在此设备或任何连接的存储设备上修改和删除媒体文件而无需用户确认。应用程序必须已被授予 READ_EXTERNAL_STORAGE 或 MANAGE_EXTERNAL_STORAGE 权限，以使此权限生效。'],
        'MANAGE_WIFI_INTERFACES': ['normal', '允许管理 Wi-Fi 接口请求之间的冲突', '允许应用程序在 Wi-Fi 接口请求无法满足而不得不拆除一个或多个其他接口时获得通知，并提供批准或拒绝请求的决定。不适用于第三方应用程序。'],
        'MANAGE_WIFI_NETWORK_SELECTION': ['normal', '允许特权管理 Wi-Fi 网络选择', '此权限用于让 OEM 允许其受信任的应用程序访问一组受特权的 wifi API，以改善 wifi 性能。允许应用程序管理与 Wi-Fi 网络选择相关的功能，如启用或禁用全局自动加入，修改连接扫描间隔，并批准 Wi-Fi 直连连接。不适用于第三方应用程序。'],
        'NEARBY_WIFI_DEVICES': ['dangerous', '通过 Wi-Fi 广告和连接到附近设备所需', '要能够通过 Wi-Fi 广告和连接到附近设备，需要此权限。'],
        'OVERRIDE_WIFI_CONFIG': ['normal', '允许修改任何 Wi-Fi 配置', '允许应用程序修改任何 Wi-Fi 配置，即使是由另一个应用程序创建的。一旦重新配置，原始创建者将无法进行进一步的修改。不适用于第三方应用程序。'],
        'POST_NOTIFICATIONS': ['dangerous', '允许应用程序发布通知', '允许应用程序发布通知。'],
        'PROVIDE_OWN_AUTOFILL_SUGGESTIONS': ['internal', '允许使用自动填充框架提供自动填充建议', '允许应用程序使用自动填充框架显示其建议。'],
        'PROVIDE_REMOTE_CREDENTIALS': ['signature', '允许从远程设备存储和检索凭据', '允许应用程序能够从远程设备存储和检索凭据。'],
        'READ_ASSISTANT_APP_SEARCH_DATA': ['normal', '允许查询助理角色可见的全局 AppSearch 数据', "允许应用程序查询助理角色可见的 AppSearch 中的全局数据。"],
        'READ_BASIC_PHONE_STATE': ['normal', '允许只读访问基本电话状态信息', '允许以非危险权限访问电话状态，包括诸如蜂窝网络类型、软件版本等信息。'],
        'READ_HOME_APP_SEARCH_DATA': ['normal', '允许查询主页角色可见的全局 AppSearch 数据', '允许应用程序查询主页角色可见的 AppSearch 中的全局数据。'],
        'READ_MEDIA_AUDIO': ['dangerous', '允许从外部存储读取音频文件', '允许应用程序从外部存储读取音频文件。'],
        'READ_MEDIA_IMAGES': ['dangerous', '允许从外部存储读取图像文件', '允许应用程序从外部存储读取图像文件。'],
        'READ_MEDIA_VIDEO': ['dangerous', '允许从外部存储读取视频文件', '允许应用程序从外部存储读取视频文件。'],
        'READ_MEDIA_VISUAL_USER_SELECTED': ['dangerous', '允许从外部存储读取用户选择的图像或视频文件', '允许应用程序从外部存储读取用户通过权限提示的照片选择器选择的图像或视频文件。应用程序可以检查此权限以验证用户是否决定使用照片选择器，而不是授予读取图像或视频的权限。不会阻止应用程序手动访问标准照片选择器。应该与 READ_MEDIA_IMAGES 和/或 READ_MEDIA_VIDEO 一起请求此权限，具体取决于所需的媒体类型。'],
        'READ_NEARBY_STREAMING_POLICY': ['normal', '允许读取附近的流媒体策略设置', '允许应用程序读取附近的流媒体策略。该策略控制设备是否允许将其通知和应用程序流式传输到附近的设备。'],
        'REQUEST_COMPANION_PROFILE_APP_STREAMING': ['normal', '允许请求与应用程序流式传输的虚拟显示相关联', '允许应用程序通过 CompanionDeviceManager 请求与能够流式传输 Android 应用程序的虚拟显示关联（ AssociationRequest.DEVICE_PROFILE_APP_STREAMING ）。不适用于第三方应用程序。'],
        'REQUEST_COMPANION_PROFILE_AUTOMOTIVE_PROJECTION': ['normal', '允许请求与汽车投影相关联的车辆头单元', '允许应用程序通过 CompanionDeviceManager 请求与能够进行汽车投影的车辆头单元关联（ AssociationRequest.DEVICE_PROFILE_AUTOMOTIVE_PROJECTION ）。不适用于第三方应用程序。'],
        'REQUEST_COMPANION_PROFILE_COMPUTER': ['normal', '允许请求与计算机共享功能相关联', '允许应用程序通过 CompanionDeviceManager 请求与计算机关联，以与其他设备共享功能和/或数据，如通知、照片和媒体（ AssociationRequest.DEVICE_PROFILE_COMPUTER ）。不适用于第三方应用程序。'],
        'REQUEST_COMPANION_PROFILE_GLASSES': ['normal', "允许请求与设备关联为“GLASSES”", '允许应用程序通过 CompanionDeviceManager 请求与设备关联为“GLASSES”。'],
        'REQUEST_COMPANION_PROFILE_NEARBY_DEVICE_STREAMING': ['normal', '允许请求将内容流式传输到附近设备', '允许应用程序通过 CompanionDeviceManager 请求从 Android 主机向附近设备流式传输内容（ AssociationRequest.DEVICE_PROFILE_NEARBY_DEVICE_STREAMING ）。不适用于第三方应用程序。'],
        'REQUEST_COMPANION_SELF_MANAGED': ['normal', '允许创建自管理伴侣设备关联', '允许应用程序创建“自管理”关联。'],
        'REQUEST_COMPANION_START_FOREGROUND_SERVICES_FROM_BACKGROUND': ['normal', '允许伴侣应用程序从后台启动前台服务', '允许伴侣应用程序从后台启动前台服务。'],
        'RUN_USER_INITIATED_JOBS': ['normal', '允许使用用户启动的作业 API', '允许应用程序使用用户启动的作业 API。'],
        'START_FOREGROUND_SERVICES_FROM_BACKGROUND': ['normal', '允许从后台启动前台服务', '允许应用程序随时从后台启动前台服务。此权限不适用于第三方应用程序，唯一的例外是如果应用程序是默认的 SMS 应用程序。否则，它只能由特权应用程序、应用程序验证器应用程序和具有任何 EMERGENCY 或 SYSTEM GALLERY 角色的应用程序使用。'],
        'START_VIEW_APP_FEATURES': ['signature', '允许启动列出应用程序功能的屏幕', '允许持有者启动屏幕，并列出应用程序功能。'],
        'SUBSCRIBE_TO_KEYGUARD_LOCKED_STATE': ['signature', '允许订阅锁定状态', '允许应用程序订阅锁定（如，显示）状态。'],
        'TURN_SCREEN_ON': ['normal', '允许打开屏幕，供家庭自动化应用程序使用', '允许应用程序打开屏幕，例如使用 PowerManager.ACQUIRE_CAUSES_WAKEUP。仅用于家庭自动化应用程序。'],
        'UPDATE_PACKAGES_WITHOUT_USER_ACTION': ['normal', '允许更新包而无需用户操作', '允许应用程序通过 PackageInstaller.SessionParams.setRequireUserAction(int) 指示不需要用户操作即可进行应用程序更新。'],
        'USE_EXACT_ALARM': ['normal', '允许无需用户许可使用精确的闹钟', '允许应用程序像使用 SCHEDULE_EXACT_ALARM 一样使用精确的闹钟，但无需从用户请求此权限。这仅适用于依赖于精确闹钟进行核心功能的应用程序。如果您的应用程序需要精确的闹钟作为用户可能或可能不使用的辅助功能，则应继续使用 SCHEDULE_EXACT_ALARM。请注意，这是一个强大的权限，应用商店可能会实施审核和审查此权限的使用政策。如果发现应用程序滥用此权限，则可能会从应用商店中移除。'],
        'UWB_RANGING': ['dangerous', '必需用于使用超宽带进行测距', '需要能够使用超宽带对设备进行测距。'],
    },

    'SPECIAL_PERMISSIONS': {
        'com.sec.android.provider.badge.permission.READ': ['normal', '在应用程序上显示通知计数', '允许在应用程序启动图标上显示通知计数或徽章，适用于三星手机。'],
        'com.sec.android.provider.badge.permission.WRITE': ['normal', '在应用程序上显示通知计数', '允许在应用程序启动图标上显示通知计数或徽章，适用于三星手机。'],
        'com.htc.launcher.permission.READ_SETTINGS': ['normal', '在应用程序上显示通知计数', '允许在应用程序启动图标上显示通知计数或徽章，适用于 HTC 手机。'],
        'com.htc.launcher.permission.UPDATE_SHORTCUT': ['normal', '在应用程序上显示通知计数', '允许在应用程序启动图标上显示通知计数或徽章，适用于 HTC 手机。'],
        'com.sonyericsson.home.permission.BROADCAST_BADGE': ['normal', '在应用程序上显示通知计数', '允许在应用程序启动图标上显示通知计数或徽章，适用于索尼手机。'],
        'com.sonymobile.home.permission.PROVIDER_INSERT_BADGE': ['normal', '在应用程序上显示通知计数', '允许在应用程序启动图标上显示通知计数或徽章，适用于索尼手机。'],
        'com.anddoes.launcher.permission.UPDATE_COUNT': ['normal', '在应用程序上显示通知计数', '允许在 Apex 上显示通知计数或徽章的应用程序。'],
        'com.majeur.launcher.permission.UPDATE_BADGE': ['normal', '在应用程序上显示通知计数', '允许在 Solid 上显示通知计数或徽章的应用程序'],
        'com.huawei.android.launcher.permission.READ_SETTINGS': ['normal', '在应用程序上显示通知计数', '允许在应用程序启动图标上显示通知计数或徽章，适用于华为手机。'],
        'com.huawei.android.launcher.permission.WRITE_SETTINGS': ['normal', '在应用程序上显示通知计数', '允许在应用程序启动图标上显示通知计数或徽章，适用于华为手机。'],
        'com.huawei.android.launcher.permission.CHANGE_BADGE': ['normal', '在应用程序上显示通知计数', '允许在应用程序启动图标上显示通知计数或徽章，适用于华为手机。'],
        'com.oppo.launcher.permission.READ_SETTINGS': ['normal', '在应用程序上显示通知计数', '允许在应用程序启动图标上显示通知计数或徽章，适用于 OPPO 手机。'],
        'com.oppo.launcher.permission.WRITE_SETTINGS': ['normal', '在应用程序上显示通知计数', '允许在应用程序启动图标上显示通知计数或徽章，适用于 OPPO 手机。'],
        'com.google.android.gms.permission.AD_ID': ['normal', '应用程序显示广告', '该应用程序使用 Google 广告 ID，可能会显示广告。'],
        'com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE': ['normal', '由 Google 定义的权限', '由 Google 定义的自定义权限。'],
        'com.google.android.c2dm.permission.RECEIVE': ['normal', '接收推送通知', '允许应用程序从云端接收推送通知。'],
        'com.android.vending.BILLING': ['normal', '应用程序具有应用内购买', '允许应用程序从 Google Play 进行应用内购买。'],
        'android.permission.ACCESS_ADSERVICES_TOPICS': ['normal', '允许应用程序访问广告服务主题', '这使应用程序能够检索与广告主题或兴趣相关的信息，可用于定向广告目的。'],
        'android.permission.ACCESS_ADSERVICES_ATTRIBUTION': ['normal', '允许应用程序访问广告服务归因', '这使应用程序能够检索与广告归因相关的信息，可用于定向广告目的。应用程序可以收集用户与广告的交互数据，例如点击或展示，以衡量广告活动的有效性。'],
        'android.permission.ACCESS_ADSERVICES_AD_ID': ['normal', '允许应用程序访问设备的广告 ID', '这是由 Google 广告服务提供的唯一、可重置的标识符，允许应用程序在保持用户隐私的同时跟踪用户行为，用于广告目的。'],
        'oppo.permission.OPPO_COMPONENT_SAFE': ['signature', 'OPPO 设备特定的权限', '用于授予应用程序访问某些受限系统级功能或组件的能力，否则由于安全原因会受到限制。此权限确保只有可信任的应用程序才能与 OPPO 系统的敏感部分进行交互。'],
        'com.huawei.permission.external_app_settings.USE_COMPONENT': ['signature', '华为设备特定的权限', '用于授予应用程序访问某些受限系统级功能或组件的能力，否则由于安全原因会受到限制。此权限确保只有可信任的应用程序才能与华为系统的敏感部分进行交互。'],

    },

    'MANIFEST_PERMISSION_GROUP': {
        'ACCOUNTS': '直接访问由账户管理器管理的账户的权限。',
        'COST_MONEY': '用于可以在没有用户直接参与的情况下使用户花费金钱的权限。',
        'DEVELOPMENT_TOOLS': '与开发功能相关的权限组。',
        'HARDWARE_CONTROLS': '用于提供对设备硬件的直接访问的权限。',
        'LOCATION': '允许访问用户当前位置的权限。',
        'MESSAGES': '用于允许应用程序代表用户发送消息或拦截用户接收的消息的权限。',
        'NETWORK': '提供对网络服务的访问权限。',
        'PERSONAL_INFO': '提供对用户私人数据（如联系人、日历事件、电子邮件等）的访问权限。',
        'PHONE_CALLS': '与访问和修改电话状态相关的权限：拦截呼出电话、读取和修改电话状态。',
        'STORAGE': '与SD卡访问相关的权限组。',
        'SYSTEM_TOOLS': '与系统API相关的权限组。',
    },
}
